# Generated by Django 5.2.6 on 2025-11-11 05:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommercialPhenotypeRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The commercial brand name, e.g., 'Black Ice'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "breeder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "required_genotypes",
                    models.JSONField(
                        help_text="JSON dictionary mapping Locus name to required genotype. Format: {'Locus Name': 'Allele1/Allele2'}"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Phenotype Recipe",
                "verbose_name_plural": "Phenotype Recipes",
            },
        ),
        migrations.CreateModel(
            name="Locus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Overbar, Onyx, Lightning",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "alleles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5),
                        default=list,
                        help_text="e.g., ['P', 'Sf', 'O', '+', 'L', 'N']",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loci",
            },
        ),
    ]
