# Generated by Django 5.2.6 on 2025-11-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="date_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="genotype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="genus",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="hybrid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="origin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="phenotype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="species",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="commercialphenotyperecipe",
            name="variant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="required_genotypes",
            field=models.JSONField(help_text="JSON dictionary..."),
        ),
    ]
