# Generated by Django 5.2.6 on 2025-11-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0002_commercialphenotyperecipe_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="required_genotypes",
            field=models.JSONField(
                blank=True,
                help_text="JSON dictionary mapping Locus name to required genotype. Format: {'Locus Name': 'Allele1/Allele2'}",
                null=True,
            ),
        ),
    ]
