# Generated by Django 5.2.6 on 2025-11-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0003_alter_commercialphenotyperecipe_required_genotypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The commercial brand name, e.g., 'Black Ice'",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
