# Generated by Django 5.2.6 on 2025-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0004_alter_commercialphenotyperecipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="phenotype",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
