# Generated by Django 5.2.6 on 2025-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0005_alter_commercialphenotyperecipe_phenotype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="genotype",
            field=models.CharField(blank=True, default="+/+", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="genus",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="name",
            field=models.CharField(
                default="",
                help_text="The commercial brand name, e.g., 'Black Ice'",
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="origin",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="phenotype",
            field=models.CharField(blank=True, default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="required_genotypes",
            field=models.JSONField(
                blank=True,
                default="{}",
                help_text="JSON dictionary mapping Locus name to required genotype. Format: {'Locus Name': 'Allele1/Allele2'}",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="species",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="variant",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
