# Generated by Django 5.2.6 on 2025-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0006_alter_commercialphenotyperecipe_genotype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="slug",
            field=models.SlugField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
