# Generated by Django 5.2.6 on 2025-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0007_alter_commercialphenotyperecipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
