# Generated by Django 5.2.6 on 2025-11-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetics_manager", "0008_alter_commercialphenotyperecipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="breeder_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
