# Generated by Django 5.2.8 on 2025-11-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genetics_manager", "0009_alter_commercialphenotyperecipe_breeder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="genotype",
            field=models.CharField(blank=True, default="+/+", max_length=255),
        ),
    ]
