# Generated by Django 5.2.8 on 2025-11-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genetics_manager", "0011_alter_commercialphenotyperecipe_required_genotypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialphenotyperecipe",
            name="required_genotypes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON dictionary mapping Locus name to required genotype. Format: {'Locus Name': 'Allele1/Allele2'}",
            ),
        ),
    ]
