# Generated by Django 5.2.7 on 2025-10-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("species", models.CharField(max_length=100)),
                ("genotype_pattern", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Cross",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosses_as_parent1",
                        to="calcRefactor.parent",
                    ),
                ),
                (
                    "parent2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosses_as_parent2",
                        to="calcRefactor.parent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Progeny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genotype", models.CharField(max_length=50)),
                (
                    "phenotype_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "cross",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calcRefactor.cross",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parent",
            name="variety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calcRefactor.variety"
            ),
        ),
    ]
