# Generated by Django 5.2.7 on 2025-10-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calcRefactor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cross",
            options={"verbose_name_plural": "Crosses"},
        ),
        migrations.AlterModelOptions(
            name="parent",
            options={"verbose_name_plural": "Parents"},
        ),
        migrations.AlterModelOptions(
            name="progeny",
            options={"verbose_name_plural": "Progeny"},
        ),
        migrations.AlterModelOptions(
            name="variety",
            options={"verbose_name_plural": "Varieties"},
        ),
    ]
