# Generated by Django 5.2.7 on 2025-10-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calcRefactor", "0002_alter_cross_options_alter_parent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossNamingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variety1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naming_rules_as_variety1",
                        to="calcRefactor.variety",
                    ),
                ),
                (
                    "variety2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naming_rules_as_variety2",
                        to="calcRefactor.variety",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cross Naming Rules",
                "unique_together": {("variety1", "variety2")},
            },
        ),
        migrations.CreateModel(
            name="ProgenyNamingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genotype_pattern", models.CharField(max_length=50)),
                ("phenotype_name", models.CharField(max_length=150)),
                (
                    "cross_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calcRefactor.crossnamingrule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Progeny Naming Rules",
                "unique_together": {("cross_rule", "genotype_pattern")},
            },
        ),
    ]
