# Generated by Django 5.2.6 on 2025-11-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calcRefactor", "0003_crossnamingrule_progenynamingrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progeny",
            name="phenotype_name",
            field=models.CharField(blank=True, default="", max_length=150),
            preserve_default=False,
        ),
    ]
