# Generated by Django 5.2.6 on 2025-11-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calcRefactor", "0004_alter_progeny_phenotype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="genus",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variety",
            name="hybrid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="variety",
            name="variant",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
