# clownfishgenetics/calcRefactor/migrations/0006_auto_20251111_2133.py

# Generated by Django 5.2.6 on 2025-11-11 21:33

from django.db import migrations, transaction


def copy_recipe_data(apps, schema_editor):
    # Get the historical versions of the models
    Recipe = apps.get_model('genetics_manager', 'CommercialPhenotypeRecipe')
    Variety = apps.get_model('calcRefactor', 'Variety')
    Clownfish = apps.get_model('calculator', 'Clownfish')

    with transaction.atomic():
        for recipe_obj in Recipe.objects.all():
            # --- Populate Variety model (calcRefactor) ---
            Variety.objects.get_or_create(
                name=recipe_obj.name,
                defaults={
                    'genus': recipe_obj.genus or "Amphiprion",
                    'species': recipe_obj.species or "ocellaris",
                    'variant': recipe_obj.variant,
                    'hybrid': recipe_obj.hybrid,
                    'genotype_pattern': "N/A",  # Needs a default value as it's required
                }
            )

            # --- Populate Clownfish model (calculator) ---
            Clownfish.objects.get_or_create(
                name=recipe_obj.name,
                defaults={
                    'genus': recipe_obj.genus or "Amphiprion",
                    'species': recipe_obj.species or "ocellaris",
                    'variant': recipe_obj.variant,
                    'hybrid': recipe_obj.hybrid,
                }
            )


def reverse_copy(apps, schema_editor):
    # Logic to remove the data if the migration is rolled back
    Variety = apps.get_model('calcRefactor', 'Variety')
    Clownfish = apps.get_model('calculator', 'Clownfish')

    Variety.objects.all().delete()
    Clownfish.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        # The exact latest dependencies for all three apps:
        ('calcRefactor', '0005_variety_genus_variety_hybrid_variety_variant'),
        ('genetics_manager', '0009_alter_commercialphenotyperecipe_breeder_name'),
        ('calculator', '0006_clownfish_hybrid_clownfish_variant'),
    ]

    operations = [
        migrations.RunPython(copy_recipe_data, reverse_copy),
    ]
