# Generated by Django 5.2.6 on 2025-09-27 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alleles', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('dominance_rules', models.JSONField(blank=True, default=dict)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alleles', to='calculator.trait')),
            ],
        ),
    ]
