# Generated by Django 5.2.6 on 2025-09-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_allele_dominance_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clownfish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('genotype', models.JSONField(default=dict)),
            ],
        ),
    ]
