# Generated by Django 5.2.6 on 2025-09-27 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0004_remove_clownfish_genotype_clownfishgenotype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clownfish",
            options={"verbose_name_plural": "Clownfish"},
        ),
    ]
