# Generated by Django 5.2.6 on 2025-11-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_alter_clownfish_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clownfish",
            name="hybrid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clownfish",
            name="variant",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
