# Generated by Django 5.2.8 on 2025-11-29 20:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Clownfish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("genus", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("variant", models.CharField(blank=True, max_length=255)),
                ("hybrid", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Clownfish",
            },
        ),
        migrations.CreateModel(
            name="CommercialPhenotypeRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The commercial brand name, e.g., 'Black Ice'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("breeder_name", models.CharField(blank=True, max_length=100)),
                (
                    "required_genotypes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dictionary mapping Locus name to required genotype. Format: {'Locus Name': 'Allele1/Allele2'}",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "phenotype",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "genotype",
                    models.CharField(blank=True, default="+/+", max_length=255),
                ),
                ("genus", models.CharField(blank=True, max_length=50)),
                ("species", models.CharField(blank=True, max_length=50)),
                ("variant", models.CharField(blank=True, max_length=255)),
                ("hybrid", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("origin", models.CharField(blank=True, max_length=50)),
                ("created_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Phenotype Recipe",
                "verbose_name_plural": "Phenotype Recipes",
            },
        ),
        migrations.CreateModel(
            name="Locus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Overbar, Onyx, Lightning",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "alleles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5),
                        default=list,
                        help_text="e.g., ['P', 'Sf', 'O', '+', 'L', 'N']",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loci",
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parents",
            },
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "inheritance_pattern",
                    models.CharField(
                        choices=[
                            ("dominant", "Dominant/Recessive"),
                            ("codominant", "Codominant"),
                            ("incomplete", "Incomplete Dominance"),
                        ],
                        default="dominant",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserGenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alleles", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("genus", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("variant", models.CharField(blank=True, max_length=255)),
                ("hybrid", models.BooleanField(default=False)),
                ("genotype_pattern", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Varieties",
            },
        ),
        migrations.CreateModel(
            name="ClownfishGenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allele1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele1_set",
                        to="cbr.allele",
                    ),
                ),
                (
                    "allele2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele2_set",
                        to="cbr.allele",
                    ),
                ),
                (
                    "clownfish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cbr.clownfish"
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cbr.trait"
                    ),
                ),
            ],
            options={
                "unique_together": {("clownfish", "trait")},
            },
        ),
        migrations.AddField(
            model_name="clownfish",
            name="genotype",
            field=models.ManyToManyField(
                through="cbr.ClownfishGenotype",
                through_fields=("clownfish", "allele1"),
                to="cbr.allele",
            ),
        ),
        migrations.CreateModel(
            name="Cross",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosses_as_parent1",
                        to="cbr.parent",
                    ),
                ),
                (
                    "parent2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosses_as_parent2",
                        to="cbr.parent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crosses",
            },
        ),
        migrations.CreateModel(
            name="Progeny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genotype", models.CharField(max_length=50)),
                ("phenotype_name", models.CharField(blank=True, max_length=150)),
                (
                    "cross",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cbr.cross"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Progeny",
            },
        ),
        migrations.AddField(
            model_name="allele",
            name="trait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alleles",
                to="cbr.trait",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="variety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cbr.variety"
            ),
        ),
        migrations.CreateModel(
            name="CrossNamingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variety1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naming_rules_as_variety1",
                        to="cbr.variety",
                    ),
                ),
                (
                    "variety2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naming_rules_as_variety2",
                        to="cbr.variety",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cross Naming Rules",
                "unique_together": {("variety1", "variety2")},
            },
        ),
        migrations.CreateModel(
            name="ProgenyNamingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genotype_pattern", models.CharField(max_length=50)),
                ("phenotype_name", models.CharField(max_length=150)),
                (
                    "cross_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cbr.crossnamingrule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Progeny Naming Rules",
                "unique_together": {("cross_rule", "genotype_pattern")},
            },
        ),
        migrations.CreateModel(
            name="GenotypePhenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phenotype", models.CharField(max_length=200)),
                (
                    "allele1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cbr.allele",
                    ),
                ),
                (
                    "allele2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cbr.allele",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phenotypes",
                        to="cbr.trait",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trait", "allele1", "allele2"],
                        name="cbr_genotyp_trait_i_79593b_idx",
                    )
                ],
                "unique_together": {("trait", "allele1", "allele2")},
            },
        ),
    ]
